export const MAIN_PAGE_ACTIVE = "PAGES/MAIN_ACTIVE"
export const WORKS_PAGE_ACTIVE = "PAGES/WORKS_ACTIVE"
export const CONTACTS_PAGE_ACTIVE = "PAGES/CONTACTS_ACTIVE"
export const TREE_PAGE_ACTIVE = "PAGES/TREE_ACTIVE"
export const LOADING_PAGE_DIS = "PAGES/LOADING_DIS"

export const MAIN_HOR = "SHOW/MAIN-HOR";

export const MAIN_HOR_HOVER_ON = "SHOW/MAIN_HOR_HOVER_ON";
export const MAIN_HOR_HOVER_OUT = "SHOW/MAIN_HOR_HOVER_OUT";

export const LEFT_DOWN = "SHOW/LEFT_DOWN";

export const REACT_INFO_STATE_TRUE = "STATE/REACT_INFO_TRUE";
export const REACT_INFO_STATE_FALSE = "STATE/REACT_INFO_FALSE";

export const REACT_INFO_SHOW_1 = "SHOW/REACT_INFO_1";
export const REACT_INFO_SHOW_2 = "SHOW/REACT_INFO_2";
export const REACT_INFO_SHOW_3 = "SHOW/REACT_INFO_3";

export const REACT_INFO_HIDE_1 = "HIDE/REACT_INFO_1";
export const REACT_INFO_HIDE_2 = "HIDE/REACT_INFO_2";
export const REACT_INFO_HIDE_3 = "HIDE/REACT_INFO_3";

export const JS_INFO_SHOW_1 = "SHOW/JS_INFO_1";
export const JS_INFO_SHOW_2 = "SHOW/JS_INFO_2";
export const JS_INFO_SHOW_3 = "SHOW/JS_INFO_3";

export const JS_INFO_HIDE_1 = "HIDE/JS_INFO_1";
export const JS_INFO_HIDE_2 = "HIDE/JS_INFO_2";
export const JS_INFO_HIDE_3 = "HIDE/JS_INFO_3";

export const JS_BASICS_RIGHT = "ARR/JS_BASICS_RIGHT";
export const JS_BASICS_LEFT = "ARR/JS_BASICS_LEFT";

export const JS_BASIC_TEXT_ANIMATION_1 = "ANIM/JS_BASIC_TEXT_ANIMATION_1";
export const JS_BASIC_TEXT_ANIMATION_2 = "ANIM/JS_BASIC_TEXT_ANIMATION_2";
export const JS_BASIC_TEXT_ANIMATION_3 = "ANIM/JS_BASIC_TEXT_ANIMATION_3";

export const JS_BASIC_TEXT_ANIMATION_1_L = "ANIM/JS_BASIC_TEXT_ANIMATION_1_L";
export const JS_BASIC_TEXT_ANIMATION_2_L = "ANIM/JS_BASIC_TEXT_ANIMATION_2_L";
export const JS_BASIC_TEXT_ANIMATION_3_L = "ANIM/JS_BASIC_TEXT_ANIMATION_3_L";

export const JS_ADV_RIGHT = "ARR/JS_ADV_RIGHT";
export const JS_ADV_LEFT = "ARR/JS_ADV_LEFT";

export const JS_ADV_TEXT_ANIMATION_1 = "ANIM/JS_ADV_TEXT_ANIMATION_1";
export const JS_ADV_TEXT_ANIMATION_2 = "ANIM/JS_ADV_TEXT_ANIMATION_2";
export const JS_ADV_TEXT_ANIMATION_3 = "ANIM/JS_ADV_TEXT_ANIMATION_3";

export const JS_ADV_TEXT_ANIMATION_1_L = "ANIM/JS_ADV_TEXT_ANIMATION_1_L";
export const JS_ADV_TEXT_ANIMATION_2_L = "ANIM/JS_ADV_TEXT_ANIMATION_2_L";
export const JS_ADV_TEXT_ANIMATION_3_L = "ANIM/JS_ADV_TEXT_ANIMATION_3_L";

export const CSS_INFO_SHOW_1 = "SHOW/CSS_INFO_1";
export const CSS_INFO_SHOW_2 = "SHOW/CSS_INFO_2";

export const CSS_INFO_HIDE_1 = "HIDE/CSS_INFO_1";
export const CSS_INFO_HIDE_2 = "HIDE/CSS_INFO_2";

export const H_ANIM_SHOW = "SHOW/H_ANIM"
export const H_ANIM_HIDE = "HIDE/H_ANIM"
export const T_ANIM_SHOW = "SHOW/T_ANIM"
export const T_ANIM_HIDE = "HIDE/T_ANIM"
export const M_ANIM_SHOW = "SHOW/M_ANIM"
export const M_ANIM_HIDE = "HIDE/M_ANIM"
export const L_ANIM_SHOW = "SHOW/L_ANIM"
export const L_ANIM_HIDE = "HIDE/L_ANIM"

export const C_ANIM_SHOW = "SHOW/C_ANIM"
export const C_ANIM_HIDE = "HIDE/C_ANIM"
export const S_ANIM_SHOW = "SHOW/S_ANIM"
export const S_ANIM_HIDE = "HIDE/S_ANIM"
export const S2_ANIM_SHOW = "SHOW/S2_ANIM"
export const S2_ANIM_HIDE = "HIDE/S2_ANIM"

export const LEFT_DOWN_STRIPES_SHOW = "SHOW/LEFT_DOWN_STRIPES"
export const LEFT_DOWN_STRIPES_SHOW_2 = "SHOW/LEFT_DOWN_STRIPES_2"
export const LEFT_DOWN_STRIPES_HIDE = "HIDE/LEFT_DOWN_STRIPES"
export const LEFT_DOWN_STRIPES_HIDE_2 = "HIDE/LEFT_DOWN_STRIPES_2"

export const SOFT_SKILLS_SHOW = "SHOW/SOFT_SKILLS"
export const SOFT_SKILLS_HIDE = "HIDE/SOFT_SKILLS"

export const SOFT_TYPE_BUT_HIDE = "HIDE/SOFT_TYPE_BUT"
export const SOFT_TYPE_BUT_SHOW = "SHOW/SOFT_TYPE_BUT"

export const SOFT_TYPE_HOVER_ON = "SHOW/TYPE_HOVER_ON"
export const SOFT_TYPE_HOVER_ON_2 = "SHOW/TYPE_HOVER_ON_2"

export const SOFT_TYPE_HOVER_OUT = "SHOW/TYPE_HOVER_OUT"
export const SOFT_TYPE_HOVER_OUT_2 = "SHOW/TYPE_HOVER_OUT_2"

export const SOFT_TEXT_ANIM = "SHOW/SOFT_TEXT_ANIM"
export const SOFT_TEXT_ANIM_END = "HIDE/SOFT_TEXT_ANIM"

export const MAIN_PAGE_EXIT = "HIDE/MAIN_PAGE_EXIT"
export const MAIN_PAGE_EXIT_2 = "HIDE/MAIN_PAGE_EXIT_2"

export const MAIN_PAGE_ENTER = "HIDE/MAIN_PAGE_ENTER"
export const MAIN_PAGE_ENTER_2 = "HIDE/MAIN_PAGE_ENTER_2"


// common tree animations //
export const TREE_ANIM_1 = "TREE/TREE_ANIM_1"
export const TREE_ANIM_2 = "TREE/TREE_ANIM_2"
export const TREE_ANIM_3 = "TREE/TREE_ANIM_3"
export const TREE_ANIM_4 = "TREE/TREE_ANIM_4"
// html tree part //
export const HTML_ANIM_5 = "TREE/TREE_HTML_ANIM_5"
export const HTML_ANIM_6 = "TREE/TREE_HTML_ANIM_6"
export const HTML_ANIM_7 = "TREE/TREE_HTML_ANIM_7"
// css tree part //
export const CSS_ANIM_5 = "TREE/TREE_CSS_ANIM_5"
export const CSS_ANIM_6 = "TREE/TREE_CSS_ANIM_6"
export const CSS_ANIM_7 = "TREE/TREE_CSS_ANIM_7"
export const CSS_ANIM_8 = "TREE/TREE_CSS_ANIM_8"
export const CSS_ANIM_9 = "TREE/TREE_CSS_ANIM_9"
// js tree part //
export const JS_ANIM_5 = "TREE/TREE_JS_ANIM_5"
export const JS_ANIM_6 = "TREE/TREE_JS_ANIM_6"
export const JS_ANIM_7 = "TREE/TREE_JS_ANIM_7"
export const JS_ANIM_8 = "TREE/TREE_JS_ANIM_8"
export const JS_ANIM_9 = "TREE/TREE_JS_ANIM_9"
export const JS_ANIM_10 = "TREE/TREE_JS_ANIM_10"
export const JS_ANIM_11 = "TREE/TREE_JS_ANIM_11"
export const JS_ANIM_12 = "TREE/TREE_JS_ANIM_12"
export const JS_ANIM_13 = "TREE/TREE_JS_ANIM_13"
export const JS_ANIM_14 = "TREE/TREE_JS_ANIM_14"
export const JS_ANIM_15 = "TREE/TREE_JS_ANIM_15"

export const JS_CLOSE = "TREE/TREE_JS_CLOSE"
export const HTML_CLOSE = "TREE/TREE_HTML_CLOSE"
export const CSS_CLOSE = "TREE/TREE_CSS_CLOSE"
export const TREE_START_CLOSE = "TREE/TREE_START_CLOSE"

export const TREE_SHOW_GIT = "TREE/TREE_SHOW_GIT"
export const TREE_HIDE_GIT = "TREE/TREE_HIDE_GIT"



export const BTN_START = "TREE/BTN_START"
export const BTN_END = "TREE/BTN_END"


export const LOADING_PAGE_HIDE = "HIDE/LOADING_PAGE"

export const TREE_PAGE_EXIT = "TREE/TREE_EXIT"
export const TREE_PAGE_EXIT_WORKS = "TREE/TREE_EXIT_WORKS"
export const TREE_PAGE_ENTER_MAIN = "TREE/TREE_ENTER_MAIN"
export const TREE_PAGE_ENTER_WORKS = "TREE/TREE_ENTER_WORKS"
