export const MAIN_HOR = "SHOW/MAIN-HOR";

export const MAIN_HOR_HOVER_ON = "SHOW/MAIN_HOR_HOVER_ON";
export const MAIN_HOR_HOVER_OUT = "SHOW/MAIN_HOR_HOVER_OUT";

export const LEFT_DOWN_HOVER_ON = "SHOW/LEFT_DOWN_HOVER_ON";
export const LEFT_DOWN_HOVER_OUT = "SHOW/LEFT_DOWN_HOVER_OUT";

export const LEFT_DOWN = "SHOW/LEFT_DOWN";

export const REACT_INFO_STATE_TRUE = "STATE/REACT_INFO_TRUE";
export const REACT_INFO_STATE_FALSE = "STATE/REACT_INFO_FALSE";

export const REACT_INFO_SHOW_1 = "SHOW/REACT_INFO_1";
export const REACT_INFO_SHOW_2 = "SHOW/REACT_INFO_2";
export const REACT_INFO_SHOW_3 = "SHOW/REACT_INFO_3";

export const REACT_INFO_HIDE_1 = "HIDE/REACT_INFO_1";
export const REACT_INFO_HIDE_2 = "HIDE/REACT_INFO_2";
export const REACT_INFO_HIDE_3 = "HIDE/REACT_INFO_3";

export const JS_INFO_SHOW_1 = "SHOW/JS_INFO_1";
export const JS_INFO_SHOW_2 = "SHOW/JS_INFO_2";
export const JS_INFO_SHOW_3 = "SHOW/JS_INFO_3";

export const JS_INFO_HIDE_1 = "HIDE/JS_INFO_1";
export const JS_INFO_HIDE_2 = "HIDE/JS_INFO_2";
export const JS_INFO_HIDE_3 = "HIDE/JS_INFO_3";

export const JS_BASICS_RIGHT = "ARR/JS_BASICS_RIGHT";
export const JS_BASICS_LEFT = "ARR/JS_BASICS_LEFT";

export const JS_BASIC_TEXT_ANIMATION_1 = "ANIM/JS_BASIC_TEXT_ANIMATION_1";
export const JS_BASIC_TEXT_ANIMATION_2 = "ANIM/JS_BASIC_TEXT_ANIMATION_2";
export const JS_BASIC_TEXT_ANIMATION_3 = "ANIM/JS_BASIC_TEXT_ANIMATION_3";

export const JS_BASIC_TEXT_ANIMATION_1_L = "ANIM/JS_BASIC_TEXT_ANIMATION_1_L";
export const JS_BASIC_TEXT_ANIMATION_2_L = "ANIM/JS_BASIC_TEXT_ANIMATION_2_L";
export const JS_BASIC_TEXT_ANIMATION_3_L = "ANIM/JS_BASIC_TEXT_ANIMATION_3_L";

export const JS_ADV_RIGHT = "ARR/JS_ADV_RIGHT";
export const JS_ADV_LEFT = "ARR/JS_ADV_LEFT";

export const JS_ADV_TEXT_ANIMATION_1 = "ANIM/JS_ADV_TEXT_ANIMATION_1";
export const JS_ADV_TEXT_ANIMATION_2 = "ANIM/JS_ADV_TEXT_ANIMATION_2";
export const JS_ADV_TEXT_ANIMATION_3 = "ANIM/JS_ADV_TEXT_ANIMATION_3";

export const JS_ADV_TEXT_ANIMATION_1_L = "ANIM/JS_ADV_TEXT_ANIMATION_1_L";
export const JS_ADV_TEXT_ANIMATION_2_L = "ANIM/JS_ADV_TEXT_ANIMATION_2_L";
export const JS_ADV_TEXT_ANIMATION_3_L = "ANIM/JS_ADV_TEXT_ANIMATION_3_L";

export const CSS_INFO_SHOW_1 = "SHOW/CSS_INFO_1";
export const CSS_INFO_SHOW_2 = "SHOW/CSS_INFO_2";

export const CSS_INFO_HIDE_1 = "HIDE/CSS_INFO_1";
export const CSS_INFO_HIDE_2 = "HIDE/CSS_INFO_2";

export const H_ANIM_SHOW = "SHOW/H_ANIM"
export const H_ANIM_HIDE = "HIDE/H_ANIM"
export const T_ANIM_SHOW = "SHOW/T_ANIM"
export const T_ANIM_HIDE = "HIDE/T_ANIM"
export const M_ANIM_SHOW = "SHOW/M_ANIM"
export const M_ANIM_HIDE = "HIDE/M_ANIM"
export const L_ANIM_SHOW = "SHOW/L_ANIM"
export const L_ANIM_HIDE = "HIDE/L_ANIM"

export const C_ANIM_SHOW = "SHOW/C_ANIM"
export const C_ANIM_HIDE = "HIDE/C_ANIM"
export const S_ANIM_SHOW = "SHOW/S_ANIM"
export const S_ANIM_HIDE = "HIDE/S_ANIM"
export const S2_ANIM_SHOW = "SHOW/S2_ANIM"
export const S2_ANIM_HIDE = "HIDE/S2_ANIM"

export const LEFT_DOWN_STRIPES_SHOW = "SHOW/LEFT_DOWN_STRIPES"
export const LEFT_DOWN_STRIPES_HIDE = "HIDE/LEFT_DOWN_STRIPES"
